### ISSUE TITLE
Надо разобраться с урлами

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/api-express#1]
Обычно всё, что относят к определённой функциональной области, предваряют префиксом: например, `posts`.

Т.е.:
* GET /posts - список всех
* GET /posts/:id - конкретный
* POST /posts/:id/likes - лайк поста и т.д.

**Comment by lowerKamaCase** [comment]
Разобрался :) в соответствии со схемой
GET /posts - список всех
GET /posts/:id - конкретный
POST /posts/:id/likes - лайк поста и т.д.
